spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}e88e3a042e6a6715844e87bd7b2158771a445e4ab74b7c2d18f861069af3cdc6'

token:
  secret: mysecret-key-for-jwt-generation-1234567890
  expiration: 864000000 # 10 days in milliseconds