spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}f89c2529b9737ffbfe3d3ac8f51f254a34098de76e166790f62464296c5eb2b1'

token:
  secret: mysecret-key-for-jwt-generation-1234567890
  expiration: 864000000 # 10 days in milliseconds